spring:
  application:
    name: API-com-Java


  datasource:
    url: jdbc:h2:mem:workshop_db
    username: sa
    password: 1234

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  h2:
    console:
      enabled: true
      path: /h2-console

server:
  port: 8081